version: "3"
services:
  texlive:
    restart: unless-stopped
    image: ghcr.io/pusnow/texlive:latest
    hostname: latex
    volumes:
        - data:/root
        - ssh:/ssh
    ports:
        - "2222:22"
    environment:
        - SSH_KEY=https://github.com/pusnow.keys
volumes:
  ssh:
  data:
