name: custom

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
env:
  CR_PATH: ghcr.io/pusnow
  DH_PATH: pusnow

jobs:
  stage1:
    strategy:
      matrix:
        image:
          [
            "alpine-gui",
            "meshcommander",
            "borg",
            "texlive",
            "qemu",
            "hugo",
            "code-server",
            "dev",
            "samba",
            "lighttpd",
            "elixir",
            "ssh",
            "jenkins",
            "actions-runner",
            "rsync",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          cd ${{ matrix.image }} && if [ -x prepare.sh ]; then ./prepare.sh; else true ; fi

      - name: Build stage1 image
        run: |
          docker build ${{ matrix.image }} --tag ${{matrix.image}}:latest

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.CR_NAME }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker tag ${{matrix.image}}:latest $CR_PATH/${{matrix.image}}:latest
          docker push $CR_PATH/${{matrix.image}}:latest

      - name: Log into Docker Hub
        run: echo "${{ secrets.DH_TOKEN }}" | docker login -u ${{ secrets.DH_NAME }} --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker tag ${{matrix.image}}:latest $DH_PATH/${{matrix.image}}:latest
          docker push $DH_PATH/${{matrix.image}}:latest

  stage2:
    needs: stage1
    strategy:
      matrix:
        image: ["virtmanager"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          cd ${{ matrix.image }} && if [ -x prepare.sh ]; then ./prepare.sh; else true ; fi

      - name: Build custom image
        run: |
          docker build ${{ matrix.image }} --tag ${{matrix.image}}:latest

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.CR_NAME }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker tag ${{matrix.image}}:latest $CR_PATH/${{matrix.image}}:latest
          docker push $CR_PATH/${{matrix.image}}:latest

      - name: Log into Docker Hub
        run: echo "${{ secrets.DH_TOKEN }}" | docker login -u ${{ secrets.DH_NAME }} --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker tag ${{matrix.image}}:latest $DH_PATH/${{matrix.image}}:latest
          docker push $DH_PATH/${{matrix.image}}:latest
