name: custom

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
env:
  ARCHS: "amd64 arm64"
  CR_PATH: ghcr.io/pusnow
  DH_PATH: docker.io/pusnow

jobs:
  stage1:
    strategy:
      matrix:
        image:
          [
            "alpine-gui",
            "meshcommander",
            "texlive",
            "qemu",
            "hugo",
            "code-server",
            "dev",
            "samba",
            "lighttpd",
            "elixir",
            "ssh",
            "jenkins",
            "actions-runner",
            "rsync",
            "stress-ng",
            "dnsmasq",
            "hostapd",
          ]
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static

      - uses: actions/checkout@v2

      - name: Declare manifest
        run: |
          buildah manifest create ${{ matrix.image }}-manifest

      - name: Prepare
        run: |
          cd ${{ matrix.image }} && if [ -x prepare.sh ]; then ./prepare.sh; else true ; fi

      - name: Build stage1 image
        run: |
          for ARCH in $ARCHS; do
            buildah bud --tag ${{matrix.image}}:latest --manifest ${{ matrix.image }}-manifest --arch "$ARCH"  ${{ matrix.image }}
          done
    
      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag ${{matrix.image}}:latest $CR_PATH/${{matrix.image}}:latest
          buildah manifest push --all ${{ matrix.image }}-manifest "docker://$CR_PATH/${{ matrix.image }}:latest"

      - name: Log into Docker Hub
        run: buildah login -u ${{ secrets.DH_NAME }} -p "${{ secrets.DH_TOKEN }}" docker.io

      - name: Push image to Docker Hub
        run: |
          buildah tag ${{matrix.image}}:latest $DH_PATH/${{matrix.image}}:latest
          buildah manifest push --all ${{ matrix.image }}-manifest "docker://$DH_PATH/${{ matrix.image }}:latest"

  stage2:
    needs: stage1
    strategy:
      matrix:
        image: ["virtmanager"]
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static

      - uses: actions/checkout@v2

      - name: Declare manifest
        run: |
          buildah manifest create ${{ matrix.image }}-manifest

      - name: Prepare
        run: |
          cd ${{ matrix.image }} && if [ -x prepare.sh ]; then ./prepare.sh; else true ; fi

      - name: Build stage1 image
        run: |
          for ARCH in $ARCHS; do
            buildah bud --tag ${{matrix.image}}:latest --manifest ${{ matrix.image }}-manifest --arch "$ARCH"  ${{ matrix.image }}
          done
    
      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag ${{matrix.image}}:latest $CR_PATH/${{matrix.image}}:latest
          buildah manifest push --all ${{ matrix.image }}-manifest "docker://$CR_PATH/${{ matrix.image }}:latest"

      - name: Log into Docker Hub
        run: buildah login -u ${{ secrets.DH_NAME }} -p "${{ secrets.DH_TOKEN }}" docker.io

      - name: Push image to Docker Hub
        run: |
          buildah tag ${{matrix.image}}:latest $DH_PATH/${{matrix.image}}:latest
          buildah manifest push --all ${{ matrix.image }}-manifest "docker://$DH_PATH/${{ matrix.image }}:latest"
