name: custom

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
env:
  IMAGE_PATH: ghcr.io/pusnow

jobs:
  stage1:
    strategy:
      matrix:
        image:
          [
            "alpine-gui",
            "meshcommander",
            "borg",
            "texlive",
            "qemu",
            "hugo",
            "code-server",
            "dev",
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build stage1 image
        run: |
          docker build ${{ matrix.image }} --tag $IMAGE_PATH/${{matrix.image}}:latest

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.CR_NAME }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker push $IMAGE_PATH/${{matrix.image}}:latest

  stage2:
    needs: stage1
    strategy:
      matrix:
        image: ["virtmanager"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build custom image
        run: |
          docker build ${{ matrix.image }} --tag $IMAGE_PATH/${{matrix.image}}:latest

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.CR_NAME }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker push $IMAGE_PATH/${{matrix.image}}:latest
