name: debian

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
env:
  CR_PATH: ghcr.io/pusnow
  DH_PATH: docker.io/pusnow

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static

      - uses: actions/checkout@v2


      - name: Declare manifest
        run: |
          buildah manifest create debian-base-manifest

      - name: Build base amd64 image
        run: |
          buildah bud --tag debian-base:latest --manifest debian-base-manifest --arch amd64 debian-base

      - name: Build base arm64 image
        run: |
          buildah bud --tag debian-base:latest --manifest debian-base-manifest --arch arm64 debian-base

      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag debian-base:latest $CR_PATH/debian-base:latest
          buildah manifest push --all debian-base-manifest "docker://$CR_PATH/debian-base:latest"

      - name: Log into Docker Hub
        run: buildah login -u ${{ secrets.DH_NAME }} -p "${{ secrets.DH_TOKEN }}" docker.io

      - name: Push image to Docker Hub
        run: |
          buildah tag debian-base:latest $DH_PATH/debian-base:latest
          buildah manifest push --all debian-base-manifest "docker://$DH_PATH/debian-base:latest"
