name: debian-kr

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"

env:
  CR_PATH: ghcr.io/pusnow
  DH_PATH: pusnow

jobs:
  debian:
    strategy:
      matrix:
        image:
          [
            "debian:buster-slim",
            "python:slim-buster",
            "php:7-buster",
            "php:7-fpm-buster",
          ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Debian image
        run: |
          docker build . --build-arg BASE_IMAGE=${{matrix.image}} --file debian.dockerfile --tag ${{matrix.image}}

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.CR_TOKEN }}" | docker login https://ghcr.io -u ${{ secrets.CR_NAME }} --password-stdin

      - name: Push image to GitHub Container Registry
        run: |
          docker tag ${{matrix.image}} $CR_PATH/${{matrix.image}}
          docker push $CR_PATH/${{matrix.image}}

      - name: Log into Docker Hub
        run: echo "${{ secrets.DH_TOKEN }}" | docker login -u ${{ secrets.DH_NAME }} --password-stdin

      - name: Push image to Docker Hub
        run: |
          docker tag ${{matrix.image}} $DH_PATH/${{matrix.image}}
          docker push $DH_PATH/${{matrix.image}}