on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tag:
        default: latest
        type: string
      path:
        required: true
        type: string
      crpath:
        required: true
        type: string
      buildargs:
        type: string
    secrets:
      CR_NAME:
        required: true
      CR_TOKEN:
        required: true
jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static

      - uses: actions/checkout@v2

      - name: Rue prepare script if exist
        run: |
          if [ -x prepare.sh ];then
            echo "Running prepare.sh"
            ./prepare.sh
          fi
        working-directory: ${{ github.workspace }}/${{inputs.path}}

      - name: Declare manifest
        run: |
          buildah manifest create ${{inputs.name}}-${{inputs.tag}}-manifest

      - name: Build base images
        run: |
          buildah bud ${{inputs.buildargs}} --tag ${{inputs.name}}:${{inputs.tag}} --manifest ${{inputs.name}}-${{inputs.tag}}-manifest --arch amd64 ${{inputs.path}}

      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag ${{inputs.name}}:${{inputs.tag}} ${{ inputs.crpath }}/${{inputs.name}}:${{inputs.tag}}
          buildah manifest push --all ${{inputs.name}}-${{inputs.tag}}-manifest "docker://${{ inputs.crpath }}/${{inputs.name}}:${{inputs.tag}}"
      # - uses: azure/container-scan@v0
      #   with:
      #     image-name: ${{ inputs.crpath }}/${{inputs.name}}:${{inputs.tag}}