name: Build Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"


jobs:
  base:
    strategy:
      matrix:
        debian-tag: ["bullseye", "bookworm"]
    uses: ./.github/workflows/docker-build.yml
    with:
      name: debian-base
      tag: ${{ matrix.debian-tag }}
      path: debian-base
      crpath: ghcr.io/pusnow
      buildargs: --build-arg DEBIAN_TAG=${{ matrix.debian-tag }}
    secrets: inherit

  debian:
    needs: base
    strategy:
      matrix:
        image:
          - name: borg
            packages: borgbackup
            cmd: borg
          - name: dnsmasq
            packages: dnsmasq iptables
            cmd: /usr/sbin/dnsmasq
          - name: hostapd
            packages: hostapd iw wireless-tools
            cmd: /usr/sbin/hostapd
          - name: vsftpd
            packages: vsftpd
            cmd: /usr/sbin/vsftpd
        debian-tag: ["bullseye", "bookworm"]
    uses: ./.github/workflows/docker-build.yml
    with:
      name: ${{ matrix.image.name }}
      path: debian-img
      tag: ${{ matrix.debian-tag }}
      crpath: ghcr.io/pusnow
      buildargs: --build-arg PS_DEBIAN_TAG=${{ matrix.debian-tag }} --build-arg DEBIAN_PKGS="${{ matrix.image.packages }}" --build-arg DEBIAN_CMD="${{ matrix.image.cmd }}"
    secrets: inherit

  custom:
    needs: base
    strategy:
      matrix:
        image:
          - name: ssh

    uses: ./.github/workflows/docker-build.yml
    with:
      name: ${{ matrix.image.name }}
      path: ${{ matrix.image.name }}
      crpath: ghcr.io/pusnow
      buildargs: --build-arg PS_DEBIAN_TAG=bullseye
    secrets: inherit

  qemu:
    needs: base
    strategy:
      matrix:
        image:
          - tag: bookworm
            debian-tag: bookworm
          - tag: latest
            debian-tag: bullseye
    uses: ./.github/workflows/docker-build.yml
    with:
      name: qemu
      path: qemu
      tag: ${{ matrix.image.tag }}
      crpath: ghcr.io/pusnow
      buildargs: --build-arg PS_DEBIAN_TAG=${{ matrix.image.debian-tag }}
    secrets: inherit

  actions-runner:
    needs: qemu
    uses: ./.github/workflows/docker-build.yml
    with:
      name: actions-runner
      path: actions-runner
      crpath: ghcr.io/pusnow
      buildargs: --build-arg PS_DEBIAN_TAG=latest
    secrets: inherit

  keepalive:
    needs: [custom, debian, qemu]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/keepalive-workflow@v1
    
