name: Build Docker Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
env:
  ARCHS: "amd64 arm64"
  CR_PATH: ghcr.io/pusnow
  DH_PATH: docker.io/pusnow

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static

      - uses: actions/checkout@v2

      - name: Declare manifest
        run: |
          buildah manifest create debian-base-manifest

      - name: Build base images
        run: |
          for ARCH in $ARCHS; do
            buildah bud --tag debian-base:latest --manifest debian-base-manifest --arch "$ARCH" debian-base
          done

      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag debian-base:latest $CR_PATH/debian-base:latest
          buildah manifest push --all debian-base-manifest "docker://$CR_PATH/debian-base:latest"

  debian:
    needs: base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - name: borg
            packages: borgbackup
            cmd: borg
          - name: dnsmasq
            packages: dnsmasq
            cmd: /usr/sbin/dnsmasq
          - name: hostapd
            packages: hostapd iw wireless-tools
            cmd: /usr/sbin/hostapd
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static
      - uses: actions/checkout@v2

      - name: Declare manifest
        run: |
          buildah manifest create ${{ matrix.image.name }}-manifest

      - name: Build images
        run: |
          for ARCH in $ARCHS; do
            buildah bud --build-arg DEBIAN_PKGS="${{ matrix.image.packages }}" --build-arg DEBIAN_CMD="${{ matrix.image.cmd }}" --tag ${{ matrix.image.name }}:latest --manifest ${{ matrix.image.name }}-manifest --arch "$ARCH" debian-img
          done

      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag ${{ matrix.image.name }}:latest $CR_PATH/${{ matrix.image.name }}:latest
          buildah manifest push --all ${{ matrix.image.name }}-manifest "docker://$CR_PATH/${{ matrix.image.name }}:latest"

  custom:
    needs: base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: 
          - meshcommander
          - texlive
          - qemu
          - hugo
          - code-server
          - dev
          - actions-runner
          - stress-ng
    steps:
      - name: Install packages
        run: |
          sudo apt update && sudo apt install -y crun qemu-user-static
      - uses: actions/checkout@v2

      - name: Declare manifest
        run: |
          buildah manifest create ${{ matrix.image }}-manifest

      - name: Build images
        run: |
          for ARCH in $ARCHS; do
            buildah bud  --tag ${{ matrix.image }}:latest --manifest ${{ matrix.image }}-manifest --arch "$ARCH" ${{ matrix.image }}
          done

      - name: Log into GitHub Container Registry
        run: buildah login -u ${{ secrets.CR_NAME }} -p "${{ secrets.CR_TOKEN }}" ghcr.io

      - name: Push image to GitHub Container Registry
        run: |
          buildah tag ${{ matrix.image }}:latest $CR_PATH/${{ matrix.image }}:latest
          buildah manifest push --all ${{ matrix.image }}-manifest "docker://$CR_PATH/${{ matrix.image }}:latest"
